### ISSUE TITLE
Hide limits element?

### ISSUE THREAD

**Issue by PMMWebDevelopment** [coderdiaz/vue-tiny-pagination#5]
Hi, and thanks for making this paginator.

However, I don't need the limits element on the right of the widget as I have to have 20 items per page for my project. Is there any way to hide it?

Many thanks

**Comment by coderdiaz** [comment]
This feature isn't available :( .. but accept any contributions :)

**Comment by coderdiaz** [comment]
Coming to next version :)

**Comment by coderdiaz** [comment]
Fixed on 6650833
